WARNING:root:Error en la conexion a la base de datos.
(psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): datos.gob.ar:80
DEBUG:urllib3.connectionpool:http://datos.gob.ar:80 "GET /api/3/action/package_show?id=cultura-mapa-cultural-espacios-culturales HTTP/1.1" 301 191
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): datos.gob.ar:443
DEBUG:urllib3.connectionpool:https://datos.gob.ar:443 "GET /api/3/action/package_show?id=cultura-mapa-cultural-espacios-culturales HTTP/1.1" 200 35234
INFO:root:Request a API exitoso.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): datos.cultura.gob.ar:443
DEBUG:urllib3.connectionpool:https://datos.cultura.gob.ar:443 "GET /dataset/37305de4-3cce-4d4b-9d9a-fec3ca61d09f/resource/01c6c048-dbeb-44e0-8efa-6944f73715d7/download/biblioteca_popular.csv HTTP/1.1" 200 511527
INFO:root:Columnas aceptadas:
dict_keys(['cod_loc', 'idprovincia', 'iddepartamento', 'categoria', 'provincia', 'localidad', 'nombre', 'domicilio', 'cp', 'telefono', 'mail', 'web'])
Columnas Rechazadas:dict_keys(['observacion', 'subcategoria', 'departamento', 'piso', 'cod_tel', 'informacion adicional', 'latitud', 'longitud', 'tipolatitudlongitud', 'fuente', 'tipo_gestion', 'a単o_inicio', 'a単o_actualizacion'])
INFO:root:Columna:cod_localidad ha sido llenada
INFO:root:Columna:id_provincia ha sido llenada
INFO:root:Columna:id_departamento ha sido llenada
INFO:root:Columna:categoria ha sido llenada
INFO:root:Columna:provincia ha sido llenada
INFO:root:Columna:localidad ha sido llenada
INFO:root:Columna:nombre ha sido llenada
INFO:root:Columna:domicilio ha sido llenada
INFO:root:Columna:codigo_postal ha sido llenada
INFO:root:Columna:telefono ha sido llenada
INFO:root:Columna:mail ha sido llenada
INFO:root:Columna:web ha sido llenada
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): datos.gob.ar:80
DEBUG:urllib3.connectionpool:http://datos.gob.ar:80 "GET /api/3/action/package_show?id=cultura-mapa-cultural-espacios-culturales HTTP/1.1" 301 191
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): datos.gob.ar:443
DEBUG:urllib3.connectionpool:https://datos.gob.ar:443 "GET /api/3/action/package_show?id=cultura-mapa-cultural-espacios-culturales HTTP/1.1" 200 35234
INFO:root:Request a API exitoso.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): datos.cultura.gob.ar:443
DEBUG:urllib3.connectionpool:https://datos.cultura.gob.ar:443 "GET /dataset/37305de4-3cce-4d4b-9d9a-fec3ca61d09f/resource/4207def0-2ff7-41d5-9095-d42ae8207a5d/download/museos_datosabiertos.csv HTTP/1.1" 200 None
INFO:root:Columnas aceptadas:
dict_keys(['cod_loc', 'idprovincia', 'iddepartamento', 'categoria', 'provincia', 'localidad', 'nombre', 'direccion', 'cp', 'telefono', 'mail', 'web'])
Columnas Rechazadas:dict_keys(['observaciones', 'subcategoria', 'piso', 'cod_area', 'latitud', 'longitud', 'tipolatitudlongitud', 'info_adicional', 'fuente', 'jurisdiccion', 'a単o_inauguracion', 'actualizacion'])
INFO:root:Columna:cod_localidad ha sido llenada
INFO:root:Columna:id_provincia ha sido llenada
INFO:root:Columna:id_departamento ha sido llenada
INFO:root:Columna:categoria ha sido llenada
INFO:root:Columna:provincia ha sido llenada
INFO:root:Columna:localidad ha sido llenada
INFO:root:Columna:nombre ha sido llenada
INFO:root:Columna:domicilio ha sido llenada
INFO:root:Columna:codigo_postal ha sido llenada
INFO:root:Columna:telefono ha sido llenada
INFO:root:Columna:mail ha sido llenada
INFO:root:Columna:web ha sido llenada
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): datos.gob.ar:80
DEBUG:urllib3.connectionpool:http://datos.gob.ar:80 "GET /api/3/action/package_show?id=cultura-mapa-cultural-espacios-culturales HTTP/1.1" 301 191
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): datos.gob.ar:443
DEBUG:urllib3.connectionpool:https://datos.gob.ar:443 "GET /api/3/action/package_show?id=cultura-mapa-cultural-espacios-culturales HTTP/1.1" 200 35234
INFO:root:Request a API exitoso.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): datos.cultura.gob.ar:443
DEBUG:urllib3.connectionpool:https://datos.cultura.gob.ar:443 "GET /dataset/37305de4-3cce-4d4b-9d9a-fec3ca61d09f/resource/392ce1a8-ef11-4776-b280-6f1c7fae16ae/download/cine.csv HTTP/1.1" 200 96427
INFO:root:Columnas aceptadas:
dict_keys(['cod_loc', 'idprovincia', 'iddepartamento', 'categoria', 'provincia', 'localidad', 'nombre', 'direccion', 'cp', 'telefono', 'mail', 'web'])
Columnas Rechazadas:dict_keys(['observaciones', 'departamento', 'piso', 'cod_area', 'informacion adicional', 'latitud', 'longitud', 'tipolatitudlongitud', 'fuente', 'tipo_gestion', 'pantallas', 'butacas', 'espacio_incaa', 'a単o_actualizacion'])
INFO:root:Columna:cod_localidad ha sido llenada
INFO:root:Columna:id_provincia ha sido llenada
INFO:root:Columna:id_departamento ha sido llenada
INFO:root:Columna:categoria ha sido llenada
INFO:root:Columna:provincia ha sido llenada
INFO:root:Columna:localidad ha sido llenada
INFO:root:Columna:nombre ha sido llenada
INFO:root:Columna:domicilio ha sido llenada
INFO:root:Columna:codigo_postal ha sido llenada
INFO:root:Columna:telefono ha sido llenada
INFO:root:Columna:mail ha sido llenada
INFO:root:Columna:web ha sido llenada
WARNING:root:(psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
